name: Ada Build and Test

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install and setup Alire package manager
      - uses: alire-project/setup-alire@v2

        # Build the project using the validation build profile to enforce static analysis and coding style.
      - run: alr build --validation


      - name: Run Ada program
        run: ./main
      
      
      
