name: Ada Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ada compiler and other dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y gnat gprbuild

     
      - name: Install FSF toolchain
        uses: alire-project/alr-install@v1
        with:
          crates: gnat_native gprbuild

      - name: Add Alire to PATH
        run: echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc && source $HOME/.bashrc

      - name: Build with Alire
        run: alr build 





     
      
      
      
