name: Ada Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ada compiler
        run: sudo apt-get install gnat
      - name: Set up stable `alr`
        uses: alire-project/setup-alire@v2

      - name: Build
        run: alr build
      - name: Compile Ada code
        run: gnatmake main.adb

      - name: Run Ada program
        run: ./main





     
      
      
      
