name: Ada Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ada compiler
        run: sudo apt-get install gnat

      - name: Compile Ada code
        run: gnatmake main.adb

      - name: Run Ada program
        run: ./main
