name: Ada Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      
      - uses: alire-project/setup-alire@v2

        # Build the project using the validation build profile to enforce static analysis and coding style.
      - run: alr build --validation

        # Build & run tests
      - run: cd test && alr build --validation && alr run

      - name: Build Ada code
        run: alire build

      - name: Run Ada program
        run: ./main
      
