name: Ada Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Alire
        run: |
          git clone https://github.com/alire-project/alire.git
          cd alire
          make build
          sudo make install
          alire --version
        shell: bash

      - name: Fetch project dependencies
        run: alire update

      - name: Build Ada code
        run: alire build

      - name: Run Ada program
        run: ./main
