name: Ada Build and Test

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ada compiler and Alire
        run: |
          sudo apt-get install gnat
          curl -sSL https://alire.ada.dev/install | bash -s -- -y
          source ~/.alire/env
        shell: bash

      - name: Fetch project dependencies
        run: alr update

      - name: Build Ada code
        run: alr build

      - name: Run Ada program
        run: ./main
      
      
      
