name: Ada Build and Test

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up stable `alr`
        uses: alire-project/setup-alire@v2

      - name: Build
        run: alr build
      
      
      
